### ISSUE TITLE
The 404 error on the latest image when testing, both local URI and the default URI 

### ISSUE THREAD

**Issue by ebildebil** [Kareadita/KavitaEmail#15]
Last night when I updated the container the email service kept giving 404 errors.
I have now switched back to image 0.1.2 which is now working.

**Comment by majora2007** [comment]
Can you provide more information? I have other users using the new image and not having issues. Are you also using the nightly release? If not, then you shouldn't update. The new updates changed API layout for the upcoming release.

**Comment by ebildebil** [comment]
Sure.  Current Kavita version in Admin Dashboard > System - Version 0.5.6.0
The Kavita server is running on Truenas scale, (True charts)
The email micro service is running on a VM -> Docker. It is installed and managed via portainer. It was using the :latest tag.

Another thing I noticed, after downgrading to 0.1.2 is that when I create a new user the email does not get sent. It does work when I click resend.

If there is anything I should provide, please let me know. I'm not really an IT guy so I may need steps to follow as well.

**Comment by majora2007** [comment]
Okay so here's the deal. If you are on nightly v0.5.6.18+, you need the latest Email service. If not, you can stay on old one (or upgrade again as I've patched back the old APIs). 

I think everything should work now, but I would recommend updating to the latest version regardless, since it now has the old APIs in the place they were expected.

**Comment by ebildebil** [comment]
Thank you. I have now used the :latest version, and tested and it is connecting and seems to work fine.I will close the issue. 24.09.2022, 20:15, "Joseph Milazzo" ***@***.***>: Okay so here's the deal. If you are on nightly v0.5.6.18+, you need the latest Email service. If not, you can stay on old one (or upgrade again as I've patched back the old APIs).I think everything should work now, but I would recommend updating to the latest version regardless, since it now has the old APIs in the place they were expected.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by ebildebil** [comment]
I'll upgrade the email service to :latest and report back.
