### ISSUE TITLE
Issue With Slashes in Env Variables

### ISSUE THREAD

**Issue by duplaja** [Kareadita/KavitaEmail#23]
My SMTP password (defined in docker-compose.yml) is the one generated by AWS SES as SMTP IAM user (unable to be changed), and contains slashes. Something like:  `xxxxx+0xxxxxxxxxxxxxx2xxuCxYx/xxxxxxJTxx/xxx`

When appsettings.json is created, the Password value is an empty string, although all others populate correctly.

My suspicion is that it has to do with sed being used on [line 7 of entrypoint.sh](https://github.com/Kareadita/KavitaEmail/blob/68c804b2a0e4254dfb2efba47c5e4c23ab18cca1/entrypoint.sh#L7) and the slashes:

**Comment by majora2007** [comment]
This is closed as we moved off env variables and to mounted config.
