### ISSUE TITLE
Add Ability To Toggle EnableSSL Via Docker Environment Variable

### ISSUE THREAD

**Issue by nickkimbrough** [Kareadita/KavitaEmail#34]
Currently, `EnableSsl` is set by true to default. I am attempting to use this software with the Proton email bridge which unfortunately has an untrusted self signed certificate, so I would like the ability to set an environment variable to toggle this setting.

I believe something like this would do it, but am not familiar enough with the rest of Docker to create a PR:
`sed -i "s/\"EnableSsl\": true/\"EnableSsl\": $SSL/" /app/config/appsettings.json`

**Comment by majora2007** [comment]
You can just mount the config volume and change it yourself.

**Comment by majora2007** [comment]
This is closed as we moved off env variables and to mounted config.
