### ISSUE TITLE
Possible encoding issue with special characters (or general AWS SES smtp issues)

### ISSUE THREAD

**Issue by duplaja** [Kareadita/KavitaEmail#40]
Issue: Emails are unable to send (give a 500 error on Kavita) when attempting to send with AWS SES SMTP.

Suspected Issue: AWS SES SMTP passwords are auto-generated, and cannot be changed. They included symbols such as + and /. I suspect these may be causing issues, perhaps while being encoded. These same credentials previously worked, with the older version of Kavita Email

Things Tried: Fresh install of Kavita Email (no luck). Tested with Google App Password / Gmail Service (worked, no issues). Tested with new SMTP credentials from AWS SES (no luck).

Error log: 
```
kavita-email | [KavitaEmail] [2023-05-06 16:05:11.369 +00:00  ] [Error] Microsoft.AspNetCore.Server.Kestrel Connection id "0HMQE9ARDERTM", Request id "0HMQE9ARDERTM:00000001": An unhandled exception was thrown by the application.
kavita-email | MailKit.Security.AuthenticationException: 535: Authentication Credentials Invalid
kavita-email |  ---> MailKit.Net.Smtp.SmtpCommandException: Authentication Credentials Invalid
kavita-email |    --- End of inner exception stack trace ---
kavita-email |    at MailKit.Net.Smtp.SmtpClient.AuthenticateAsync(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)```

**Comment by duplaja** [comment]
Updated with more info: It seems to be AWS SES specific, rather than special characters.

I was able to test with a gmail account, with a password both with and without slashes and plus symbols, and had no issues either time.

**Comment by fluxis** [comment]
I am having this issue as well and my email host is with smtp2go.

**Comment by fluxis** [comment]
Issue seems to be present stating in 0.1.16 .. rolling back to 0.1.15 resolved the issue.

And yes I am testing with the same settings in both the old way using variables and the new way with the mounted volume (docker).

**Comment by majora2007** [comment]
This issue was due to an issue with SenderAddress being used for Auth. v0.1.19.0 has been confirmed to solve it.
