### ISSUE TITLE
Trying to use a hotmail account to send to Kindle or?

### ISSUE THREAD

**Issue by 9acca9** [Kareadita/KavitaEmail#44]
HI.
I really dont understand what i need to do here.
I want to send the ebooks to my kindle mail. 
-I need to config a specific mail in my amazon account? If yes, which?

I already was using Calibre-web and there i have to config one of my authorized emails (i use a hotmail account for that). But here i dont know how to config the hotmail account or if i can just authorize a kavita email account (which i dont have).

If somebody can help me i will be glad.
Thanks.

**Comment by majora2007** [comment]
You need to fill in the information in config/appsettings.json with your SMTP provider. You can google SMTP for hotmail and pretty easily set it up.

**Comment by 9acca9** [comment]
Thanks, i have the info of the smtp, but can you please share a file format for the email config.
I mean, for example, this is my appsettings.json now:
```
{
  "TokenKey": "abeatifulToken",
  "Port": 5000,
  "IpAddresses": "",
  "BaseUrl": "/"
}
```
how i add the smtp information here?
Thanks.

**Comment by 9acca9** [comment]
Oh, i see.
Now is working!!!!
But i have two question more, one is this:
In the 
`"TokenKey": "super secret unguessable key",`

Here i put whatever i want? i mean, i leave like that and is working.

And in the other hand, i never run a docker thing, so i install docker etc. But, i will like to run without docker.
I see in the wiki this:
```
Non-Docker

    Open appsettings.json in config/
    Under SMTP, fill out the required settings that are blank.
    Start KavitaEmail.exe or ./KavitaEmail

```

i dont find KavitaEmail... 
(im in linux).
