### ISSUE TITLE
Is it necessary for everyone to include the email address on Amazon?

### ISSUE THREAD

**Issue by 9acca9** [Kareadita/KavitaEmail#46]
One more question.
Is it completely necessary that in order for my family and friends to receive the books on their device that they include the mailing email (i mean the one i configured on smtp in appsettings.json) among those authorized on Amazon?

I ask this because many will not want to go into amazon settings, etc.

And I remember that there was a possibility, at some point, I don't know if it still exists to send to make an email arrive as "sent by someone else" and not by the one who originally sent the email. Or maybe there is another way.

**Comment by majora2007** [comment]
Each Kindle has it's own email associated with it. You need to configure that for the user account under devices. This is covered on the wiki.

**Comment by majora2007** [comment]
You must also white list the email that is being sent from. It is not something I can control.

**Comment by 9acca9** [comment]
"You must also white list the email that is being sent from". I was talking about this.  I remember that at least time ago, there was a way to send mails acting like i say before. Nevermind.
 Ok, thanks for your work!
