### ISSUE TITLE
Add option to not verify/validate SSL certificates.

### ISSUE THREAD

**Issue by FibreTTP** [Kareadita/KavitaEmail#48]
I am attempting to use ProtonMail Bridge in [Docker](https://github.com/shenxn/protonmail-bridge-docker) as the SMTP service for KavitaEmail.

As stated in #34, ProtonMail does not expect users to connect to their Bridge instance from different devices, and thus only signs their certificate to be valid on 127.0.0.1.

Using the following configuration:
<details><summary>appsettings.json</summary>

```
...
"SMTP": {
    "Host": "<REDACTED>",
    "Port": "25",
    "UserName": "<REDACTED>",
    "Password": "<REDACTED>",
    "SenderAddress": "<REDACTED>",
    "SenderDisplayName": "Kavita",
    "AllowSendTo": true,
    "SizeLimit": 26214400,
    "EnableSsl": false
  }
}
```
</details>

with `EnableSsl` either `true`, `false`, or not set at all outputs the following message in the log:

<details><summary>output</summary>

```
...
[KavitaEmail] [2023-07-03 20:20:35.139 +00:00  ] [Error] Microsoft.AspNetCore.Server.Kestrel Connection id "0HMRS0BQJFE9E", Request id "0HMRS0BQJFE9E:00000001": An unhandled exception was thrown by the application.
MailKit.Security.SslHandshakeException: An error occurred while attempting to establish an SSL or TLS connection.

The host name ([REDACTED]) did not match the name given in the server's SSL certificate (127.0.0.1).

 ---> System.Security.Authentication.AuthenticationException: The remote certificate was rejected by the provided RemoteCertificateValidationCallback.
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
...
```
</details>

Changing the port as you suggesting in #12 won't fix anything as port 25 (mapped to 1025) is the only port listened to by ProtonMail Bridge, and Bridge requires all connections to be secured with STARTTLS. 

Having the option to disable remote server SSL certificate validation would allow us Bridge hosters to use KavitaEmail.

**Comment by OuterWinnie** [comment]
I would also appreciated this option.

**Comment by acoffman87** [comment]
I would also like this options as well, my synology NAS runs my email relay and I am unable to utilize this app until there is an option to not validate the certificates

**Comment by majora2007** [comment]
I took a look at this and have a binary built, would anyone be willing to test it? Just let me know the platform and I'll upload here. I hooked up the appsetting.json EnableSsl to disable SSL completely.

**Comment by FibreTTP** [comment]
@majora2007 I'm on AMD64 Linux, though I usually use Docker to run everything. I assume I can run the binary in a plain Ubuntu test container, provided the `appsettings.json` file and `templates` directory are mounted at `/app/config`, since that's what the Dockerfile and `entrypoint.sh` script seems to do?

**Comment by majora2007** [comment]
ARM64: https://we.tl/t-no67PLKLkE
Linux64: https://we.tl/t-mCynImtJCu

Try this. Yes, you can run the binary and use the mounted app/config directory or just copy that into the unzipped folder.

**Comment by FibreTTP** [comment]
@majora2007 Could you please read the email I've sent you.

**Comment by majora2007** [comment]
HI @FibreTTP just following up on the build you got if it fixed the issue or not?

**Comment by majora2007** [comment]
If anyone else can help test, I've reuploaded the binaries as a pre-release:
https://github.com/Kareadita/KavitaEmail/releases/tag/v0.1.26.0

**Comment by FibreTTP** [comment]
Hey @majora2007, thanks for all your help.

The binary works perfectly. Setting `EnableSsl` to false in `appsettings.json` allows my Kavita instance to send emails. You can close this issue when the image gets pushed.

Thanks!

**Comment by majora2007** [comment]
Perfect, I'll get a release out asap. Thanks again for testing it out.
