### ISSUE TITLE
Kavita Email Error

### ISSUE THREAD

**Issue by Shadow229** [Kareadita/KavitaEmail#49]
Upgraded to the latest branch and when trying to send email I get a 500 error. 

Hitting test gives me the below error:

Email Service Url did not respond.
 Call failed with status code 500 (Internal Server Error): GET http://192.168.178.102:5003/api/test?adminEmail=<myEmail>&sendEmail=True

Only thing I can see in the log that looks erroneous is this section:

[KavitaEmail] [2023-07-12 16:42:49.952 +01:00  ] [Error] Microsoft.AspNetCore.Server.Kestrel Connection id "0HMS2TQISKKQG", Request id "0HMS2TQISKKQG:00000001": An unhandled exception was thrown by the application.
System.InvalidOperationException: Failed to convert configuration value at 'SMTP:Port' to type 'System.Int32'.

Rolling back to version 0.1.15 resolves and works fine.

**Comment by majora2007** [comment]
Hello, can you share the SMTP Port value in your KavitaEmail appsetting.json? This is saying that the emailer cannot covert the SMTP port to a number, which it needs to be.

**Comment by Shadow229** [comment]
KavitaEmail doesn't have a data directory on unraid for me to find appsetting.json. Took a look in the container directly but could do with some guidance to find the file.

From the docker app I have the SMTP_PORT value filled in as below:

![image](https://github.com/Kareadita/KavitaEmail/assets/55843220/72f500a3-cf7b-426e-aba5-30f9e2902595)

**Comment by Shadow229** [comment]
Weird - it was a fresh pull to latest, something must have carried over strange in my docker container. I've just completely removed the container and got a fresh one from CA and the env variables are gone - updated the appsettings.json as you suggested and its working again.

Thanks for the quick replies!
