### ISSUE TITLE
Social media URLs in the template make deliverability poor in the OOBE

### ISSUE THREAD

**Issue by HammyHavoc** [Kareadita/KavitaEmail#53]
I spent a good two hours trying to figure out why the deliverability was so poor, and it comes down to a lot of social media URLs relative to very little text. As a user-friendly default, it would make a lot of sense to add a boolean in the config to toggle these.

Especially when you consider that the average user installing this is going to have little to no sender reputation in terms of domain. These don't seem like very user-friendly defaults relative to the insistence of including functional email in an apparent attempt to be user-friendly.

**Comment by HammyHavoc** [comment]
Essentially, a lot of URLs in an email means worse deliverability. Depending on how specific email anti-spam systems function, especially if those URLs are not to the domain that's sending the email, and the sending domain has little to no sending reputation. The amount of text relative to the number of links is another factor to consider.

The other big red flag for a lot of anti-spam systems is different sending domains sending out more-or-less the same content with outbound links, in this case, the hyperlinked social media icons. So if there's `x` number of Kavita servers sending out emails with the same hyperlinks in to to users who have never received email from that address or domain before, it's going to look like some kind of automated spam to most anti-spam systems. Ergo, it's much better to keep it purely URLs related to the sending domain.

I'm also not sure if there's much value to the end-user with those social media icons, especially as they're always going to be users who are being invited to a server, and the server admin is already going to know about what there is for Kavita as they're the ones who installed it. Furthermore, when those users do confirm their accounts and go through to the server's web-app, they'll see the Kavita logo, so it's not really a secret that "hey, this is Kavita if you were wondering".

The hyperlinked social media icons probably make more sense within the web-app in the user settings area alongside stuff like the API and OPDS URL for people to "get help" or "find out more". However, maybe it makes more sense for end-users to ask their server admin about problems, otherwise those social media links might get deluged with support queries for problems that only the server admin can deal with. Only saying all this because I've seen it happen on other projects.

Just to confirm, you do mean an `@gmail.com, yes?

**Comment by majora2007** [comment]
From my understanding, you're using a self hosted provider or a smaller one, rather than something like Proton mail or a Gmail account, like most of the users, so for you. Hence these social media urls increase the chances of being identified as spam. 

If that's the case, I think it would be fine for you to edit the templates directly to remove any content to better suit your needs. I don't care to provide toggle switches to differentiate emails from Kavita vs something else. 

The emails are in config/templates and as long as you don't remove the {{variable}} within the template, you can customize it as you see fit for your server.

**Comment by HammyHavoc** [comment]
I'm using Google Workspace with my own domain, but that doesn't have anything to do with it being an unusual and inappropriate default template. I would imagine most users aren't using free Gmails or Protonmail and are running their own domain if `/r/selfhosted` and its ilk are anything to go by.

Please understand, I think the rest of Kavita is excellent, I might come across as snobby over this and the default email provider instead of native SMTP, but it's very close to being perfect.

**Comment by majora2007** [comment]
Right, but a solution is present already. You can customize the email templates out of the box. 

I can reopen the issue if anyone else wants to chime in, but I personally do not want to remove the social media icons from the emails for the out of the box experience. 

Perhaps you can open a post on the feature request site and we can see by upvotes if there is a community need. If there is, that could sway my decision to invest the time.
